
user1 = User.create(name: 'one', email: 'one@exam.com', password: 'one', password_confirmation: 'one', admin: true )
user2 = User.create(name: 'two', email: 'two@exam.com', password: 'two', password_confirmation: 'two', admin: false )
user3 = User.create(name: 'three', email: 'three@exam.com', password: 'three', password_confirmation: 'three', admin: false )
user4 = User.create(name: 'four', email: 'four@exam.com', password: 'four', password_confirmation: 'four', admin: false )
user5 = User.create(name: 'five', email: 'five@exam.com', password: 'five', password_confirmation: 'five', admin: false )
user6 = User.create(name: 'six', email: 'six@exam.com', password: 'six', password_confirmation: 'six', admin: false )
user7 = User.create(name: 'seven', email: 'seven@exam.com', password: 'seven', password_confirmation: 'seven', admin: false )
user8 = User.create(name: 'eight', email: 'eight@exam.com', password: 'eight', password_confirmation: 'eight', admin: false )
user9 = User.create(name: 'nine', email: 'nine@exam.com', password: 'nine', password_confirmation: 'nine', admin: false )
user10 = User.create(name: 'nine', email: 'ten@exam.com', password: 'ten', password_confirmation: 'ten', admin: false)

tag1 = Tag.create(tag_name: "提出物")
tag2 = Tag.create(tag_name: "資料作成")
tag3 = Tag.create(tag_name: "課題")
tag4 = Tag.create(tag_name: "研修")
tag5 = Tag.create(tag_name: "勉強会")
tag6 = Tag.create(tag_name: "会議")
tag7 = Tag.create(tag_name: "委員会")
tag8 = Tag.create(tag_name: "行事")
tag9 = Tag.create(tag_name: "外出")
tag10 = Tag.create(tag_name: "管理")

Task.create(title:'task1', user: user1, content: 'test_content1', end_time:'002023-01-30T00:00', status: :completed , priority: :medium, tags: [tag1])
Task.create(title:'task2', user: user2, content: 'test_content2', end_time:'002023-02-30T00:00', status: :completed , priority: :medium, tags: [tag2])
Task.create(title:'task3', user: user3, content: 'test_content3', end_time:'002023-03-30T00:00', status: :completed , priority: :medium, tags: [tag3])
Task.create(title:'task4', user: user4, content: 'test_content4', end_time:'002023-04-30T00:00', status: :in_progress , priority: :low, tags: [tag4])
Task.create(title:'task5', user: user5, content: 'test_content5', end_time:'002023-05-30T00:00', status: :in_progress , priority: :low, tags: [tag5])
Task.create(title:'task6', user: user6, content: 'test_content6', end_time:'002023-06-30T00:00', status: :in_progress , priority: :low, tags: [tag6])
Task.create(title:'task7', user: user7, content: 'test_content7', end_time:'002023-07-30T00:00', status: :not_started , priority: :high, tags: [tag7])
Task.create(title:'task8', user: user8, content: 'test_content8', end_time:'002023-08-30T00:00', status: :not_started , priority: :high, tags: [tag8])
Task.create(title:'task9', user: user9, content: 'test_content9', end_time:'002023-09-30T00:00', status: :not_started , priority: :high, tags: [tag9])
Task.create(title:'task10', user: user10, content: 'test_content10', end_time:'002023-10-30T00:00', status: :not_started, priority: :high, tags: [tag10])